# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7995408a42337a880025894f182cc49f8b5cb22ff34d254f72499013170d089a8a436e65c5f87c5b7f9f08446db8aaa628d79174cbb4d6121ede3e34ad572a4

test:
  secret_key_base: d975f4f4de760906c5081d04ce20f2fb8197082cc9a16466c943cc548d672bc21ec7efb33fa451d9c270622b57e6c469419802468dc0a7122eba2146c09bb29f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
